export interface UserResponse {
    id: string,
    image: string,
    createdAt: Date,
    updatedAt: Date,
    deletedAt: Date,
    password: string,
    name: string,
    slug: string,
    firstName: string,
    lastName: string,
    email: string,
    validated: boolean,
    birthDate: Date,
    gender: any,
    phone: string,
    country: any,
    city: string,
    address: string,
    postalCode: string,
    commercialCommunications: boolean,
    legitimateInterest: boolean,
    termsAndConditions: boolean
}